### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by merkinron** [sohamdodia/dynamodb-to-elasticsearch#2]
I'm trying to use dynamodb-to-elasticsearch. though some parameters aren't clear enough:
1. Does ```es_domain``` mean the "Domain Arn"?
2. What is the ```indiceName``` parameter? it's not clear at all what to put in this parameter.

would be great if anyone can help:)
Ron

**Comment by sohamdodia** [comment]
`es_domain` is the name of the domain. When you create a new domain in elastic search service of aws, you will be asked to enter domain name and that name is `es_domain`.

`indiceName` is the name of indice on which you can perform operations like search,sum etc. If your indice name is **data** and you want to perform simple search operation then url will be like this:  
http://your_endpoint/**data**/_search
